# Patch untuk backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: express-backend
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: development
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
---
# Patch untuk frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: react-frontend
          imagePullPolicy: Always
          env:
            - name: VITE_API_URL
              value: "http://backend:8000"
---
# Patch untuk HPA (nonaktifkan di dev)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
$patch: delete
